### ISSUE TITLE
Unspecified Failure

### ISSUE THREAD

**Issue by zveda** [KarolTrzeszczkowski/Inter-Wallet-Transfer-EC-plugin#15]
Getting a lot of 'Unspecified Failure' transactions. electroncash -v gives this output every time an error occurs:

|1887.748| |09| [InterWalletTransfer.Transfer] Could not get recipient_address; recipient wallet may have been cleaned up, aborting send_tx

Often, 10-12 transactions will succeed, then they will all fail until a new block comes. At this point more transactions will go through. Sometimes, only one transaction goes through before a run of these 'Unspecified Failure' transactions. 

Not sure what I am doing wrong. I am using the newest EC (4.0.9) and I've set the plugin to send about 100 transactions per hour. I've tried other speeds with no success.

**Comment by cculianu** [comment]
Very strange -- that error occurs when it can't create new addresses.

I'll look into it.

**Comment by molecular** [comment]
Running into this.

Very strange, InterWalletTransfer had been running for half an hour (on 2 different wallets in parallel) without issue, then this error appeared in both wallets. It also appears when I restart (on only 1 of the wallets to rule that out).

I rebuilt the history of both source and destination wallets (although destination wallet isn't used afaik, just the xpub)

All previous txs are now confirmed, but the problem still occurs.

Aha! I tried switching to a different electrum server. That fixed it!!!

Switching back to original server: error occurs again.

Restarted the failing server (happens to be my own): error still occurs.

Ok, now switching back to previously-working server: problem OCCURS again. wtf? So maybe it's not server-related after all?

Anyway, after a lot of back and forth, it seems to me the problem is simply intermittent, I cannot pinpoint it to electrum server or confirmation state of previous txs, but I have a hunch if you go slow (<1 tx per minute) it happens less.

**Comment by zveda** [comment]
I made my own fork about five years ago for this bug; you can check it out https://github.com/zveda/Inter-Wallet-Transfer-EC-plugin

I haven't tested it in years though.

**Comment by cculianu** [comment]
Does that fork fix it? Can you test molecular? Maybe @KarolTrzeszczkowski if he'e still active and see about merging the fix?

**Comment by zveda** [comment]
Ah I remember now, my initial fix he merged. Then the fork happened because I wanted to make every transactions 1-input-to-2-outputs (like a normal bch transaction), and Karol wanted to do more research about whether that is actually beneficial for privacy.

**Comment by molecular** [comment]
> Then the fork happened because I wanted to make every transactions 1-input-to-2-outputs (like a normal bch transaction)

dude!!! I absolutely want this!

these 1-1 txs are so obviously from the one person currently migrating his wallet that it hurts.

This suggestion is the perfect solution to that problem!

I want it. I want bad. I'll pay if necessary!

**Comment by zveda** [comment]
For anyone that happens upon this thread,
https://github.com/zveda/Inter-Wallet-Transfer-EC-plugin/releases/tag/1.6
is new release for the above mentioned plugin, now working with newer Electron Cash versions.

**Comment by molecular** [comment]
> Does that fork fix it? Can you test molecular?

yes, I tested @zveda s 1.6 and it both fixes the bug and adds this awesome 2->2 feature he mentioned above.
