### ISSUE TITLE
Recommended name: bijective send

### ISSUE THREAD

**Issue by fortran77** [KarolTrzeszczkowski/Inter-Wallet-Transfer-EC-plugin#4]
It's great to see this implemented! I've been hoping it would be done. A couple of previous proposals:

https://github.com/mycelium-com/wallet-android/issues/374
https://github.com/spesmilo/electrum/issues/2175

I think "bijective send" would be a good short name for this feature. See, for example, "[Bijection](https://en.wikipedia.org/wiki/Bijection)".

Also please note additional ideas in the above-cited issues for future consideration.

**Comment by KarolTrzeszczkowski** [comment]
I really love the name you've proposed, it's a natural and very fitting name. 

However I think that the name is exclusively understandable for computer scientists, mathematicians and physicists (I am a physicist). It's completely encrypted from lawyers, traders and any other people. 

I would totally go for it if the target audience was made of those who are already familiar with this term. I would go for a code refactor, and name functions like this. But I'd keep the name Inter wallet transfer in the user interface as almost nobody would use it otherwise.
